name: Auto-merge dependencies
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  auto-merge:
    uses: dallay/common-actions/.github/workflows/dependabot-auto-merge.yml@v2.0.0
    with:
      target: squash
      approve: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}